@startuml
'https://plantuml.com/sequence-diagram
class MobEnemy {
'普通敌机类
    + MobEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + shoot():List<BaseBullet>
    + dropProp():BaseProp
}
EnemyAircraft <|-- MobEnemy

class SuperEnemy {
'精英敌机类
    - shootNum:int
    - power:int
    - direction:int
    - shoot_speed:int

    + SuperEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + shoot():List<BaseBullet>
    + dropProp():BaseProp
}
EnemyAircraft <|-- SuperEnemy

abstract class EnemyAircraft {
    + EnemyAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + {abstract} dropProp():BaseProp
}
abstract class AbstractAircraft {
}
AbstractAircraft <|-- EnemyAircraft

interface EnemyFactory{
    + {abstract} createEnemy():EnemyAircraft
}
class MobEnemyFactory {
    + createEnemy():EnemyAircraft
}
class SuperEnemyFactory {
    + createEnemy():EnemyAircraft
}

EnemyFactory<|.. MobEnemyFactory
EnemyFactory<|.. SuperEnemyFactory

MobEnemyFactory ..> MobEnemy:"«create»"
SuperEnemyFactory ..> SuperEnemy:"«create»"
Game ..> EnemyFactory
Game ..> EnemyAircraft

@enduml
