@startuml
'https://plantuml.com/sequence-diagram

class HeroAircraft {
'英雄机类
    - {static} heroAircraft:HeroAircraft
    - HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + {static} getInstance():HeroAircraft
}
HeroAircraft --> HeroAircraft
BaseGame --> HeroAircraft

@enduml