@startuml
'https://plantuml.com/sequence-diagram

class Game {
    # {abstract} getAbstractEnemyAircraft():AbstractEnemyAircraft
    # {abstract} controlDifficulty():void
    + creatBossEnemy():void
}


class EasyGame {
    # getAbstractEnemyAircraft():AbstractEnemyAircraft
    # controlDifficulty():void
    + creatBossEnemy():void
}

class NormalGame {
    - enemyHpAdd:int
    - enemySpeedAdd:int
    + NormalGame()
    # getAbstractEnemyAircraft():AbstractEnemyAircraft
    # controlDifficulty():void
}

class DifficultGame {
    - enemyHpAdd:int
    - enemySpeedAdd:int
    + DifficultGame()
    # getAbstractEnemyAircraft():AbstractEnemyAircraft
    # controlDifficulty():void
}

Game <|-- EasyGame
Game <|-- NormalGame
Game <|-- DifficultGame


@enduml