@startuml
'https://plantuml.com/sequence-diagram

class BombProp {
'发布者 publisher
    - subscribers:List<Subscriber>
    + setSubscribers(List<Subscriber> subscribers):void
    + notifyAllSubscriber(): void
    + activeProp(HeroAircraft):void
}
interface Subscriber{
'订阅者接口'
    + {abstract}update():void
}

BombProp o--> Subscriber
Game --> BombProp
Game ..> AbstractFlyingObject
Subscriber <|-- AbstractFlyingObject

class AbstractFlyingObject {  /'订阅者'/
    + update():void
}
@enduml